### ISSUE TITLE
Most of the tests are failing

### ISSUE THREAD

**Issue by dmitraver** [ktoso/akka-raft#78]
I've discovered that most of tests(not multi jvm) are failing right now with the following message:

```
[ERROR] [10/09/2015 10:59:35.292] [raft-test-akka.actor.default-dispatcher-3] [akka://raft-test/user] assertion failed
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:165)
	at pl.project13.scala.akka.raft.model.ReplicatedLog.entriesBatchFrom(ReplicatedLog.scala:78)
	at pl.project13.scala.akka.raft.protocol.RaftProtocol$AppendEntries$.apply(RaftProtocol.scala:49)
	at pl.project13.scala.akka.raft.Leader$$anonfun$replicateLog$1.apply(Leader.scala:118)
	at pl.project13.scala.akka.raft.Leader$$anonfun$replicateLog$1.apply(Leader.scala:114)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:153)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:306)
	at pl.project13.scala.akka.raft.Leader$class.replicateLog(Leader.scala:114)
	at pl.project13.scala.akka.raft.RaftActor.replicateLog(RaftActor.scala:12)
	at pl.project13.scala.akka.raft.Leader$class.sendHeartbeat(Leader.scala:110)
	at pl.project13.scala.akka.raft.RaftActor.sendHeartbeat(RaftActor.scala:12)
	at pl.project13.scala.akka.raft.Leader$class.startHeartbeat(Leader.scala:103)
	at pl.project13.scala.akka.raft.RaftActor.startHeartbeat(RaftActor.scala:12)
	at pl.project13.scala.akka.raft.Leader$$anonfun$3.applyOrElse(Leader.scala:20)
	at pl.project13.scala.akka.raft.Leader$$anonfun$3.applyOrElse(Leader.scala:16)
       ....
```

I think its somehow connected to the recent fixes. I will look into that as well.

**Comment by colin-scott** [comment]
The log indices have changed (to 1-indexing), but the tests haven't.
Definitely need to update the tests! Should be fairly straightforward.

**Comment by dmitraver** [comment]
@colin-scott Thx for clarifying! I will fix them as well.

**Comment by dmitraver** [comment]
@ktoso Hi! I was able to rewrite some of the broken tests like FollowerTest using a message subscription however I have a problem that the tests are passed only when I run **anyone** of them. If I run **all** tests from one class some of them fail. The reason for this is that once the cluster is started its shared by all tests and when the leader is elected we no longer get messages like "BecomeFollower" as all nodes are already in this state. I tried to remove/add new members after each test to the cluster so that they can become followers again and notify us about the change but it didn't help. Also tried to stop all members before each test and start them again but this also didn't help at all. Is there any possible way to have a new cluster setup for each test other than what I listed? It really slows me down cause I think I already tried everything :)
